export interface IFullPost{
    nid: string,
    vid: string,
    type: string,
    language: string,
    title: string,
    uid: string,
    status: string,
    created: string,
    changed: string,
    comment: string,
    promote: string,
    sticky: string,
    tnid: string,
    translate: string,
    uri: string,
    body?: object,
    name?: string,
    picture?: string
}